### PR TITLE
Update prettier-config on trailing comma

### PR DESCRIPTION
**Pull request by Luxiyalu**
Can we have "all" for trailingComma -- makes it much easier to work with structures.

### CODE REVIEW

**Comment by proxi** [comment]
Can you please give example and arguments? 'es5' already works for structures.

**Comment by Luxiyalu** [comment]
After running prettier with current config, this is what I get for diff:

Screen Shot 2020-06-01 at 10 14 50 AM

It would be nicer for both development and git diff to not include these changes when related data is updated. @proxi

**Comment by proxi** [comment]
I have mixed feelings about it. On one hand, it is nicely consistent with arrays and structures; on the other hand, this is not correct JavaScript and won't work in some contexts without transform (it is https://github.com/tc39/proposal-trailing-function-commas stage 4 proposal). We also do not use it in any of twist-web, todoist-web currently. Having multiple ordered arguments is not a case that should be encouraged, too.

Overall, I'd vote for no 👎 but I won't object strongly if most of team prefers it.

**Comment by gnapse** [comment]
I'm not super strongly about it (because it is less common than the need for it in arrays and object literals). It is also true that adding too much arguments to a function is not advisable, and it gets to a point where it is better to set it so that all arguments are properties in a single object argument.

However, even with a small number of arguments this is beneficial when you call a function and the arguments expressions are long enough to make it a multi-line.

```
someFunction(
  aVeryLongExpressionHere,
  andAVeryLongOneOverHere,
)
```

Also there may be functions like this one:

```typescript
function fn(...elements: any[]) { /* ... */ }
```

That can be called with lots of arguments, and are also prone to have more arguments added in the future.

Overall I think I'm in favor. I'm a huge fan of trailing commas overall.

**Comment by gnapse** [comment]
I'm also not sure if this is invalid JavaScript. Both Firefox and Chrome consoles accepted this function definition:

```js
function fn(a,b,c,) { console.log({ a, b, c }) }
```

Browsers do not typically support what's not yet accepted in JS. It is also mentioned as introduced officially in ES2017 [ref](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Trailing_commas#Trailing_commas_in_functions).

**Comment by proxi** [comment]
> It is also mentioned as introduced officially in ES2017

True, my reference was outdated.

**Comment by gnapse** [comment]
Also wanted to mention that this probably requires a version number increase in this package. Not sure if a breaking change (e.g. `2.0.0`) or a minor version change (e.g. `1.1.0`).

And if we accept this, we need to take care of upgrading the other projects (I can do it, just mentioning it to make sure we're aligned in the implications).

**Comment by proxi** [comment]
I wouldn't keep religious about major-minor, otherwise we'll soon hit 42.0.0.

**Comment by Luxiyalu** [comment]
Ok, it looks like arrays and objects at least always have trailing comma. For function parameters, I don't feel as strongly, either against or pro. So if no one else feel strongly about it either, I'll just close this in a day.

**Comment by gnapse** [comment]
> otherwise we'll soon hit 42.0.0.

I "kinda" agree, but technically this is a public package, and it should not upgrade with breaking changes. For example, in a project like Reactist we probably won't keep a `package-lock.json` and if this is a patch or even minor version upgrade, it may be that Reactist become outdated with respect to how its code is formatted when installed and it picks up a newer version that changes the settings. We should respect semantic versioning.

Also, I hope we do not go about changing the settings in this package so often, so the v42 seems far fetched. It is normal now to question one or two things since we're introducing it.

**Comment by henningmu** [comment]
I'm in favor of this rule as it aligns nicely with the trailing comma in objects and other structures.

I'm also in favor of applying "real" semantic versioning here and release it as v2. Even if we reach v42 in a couple of months I don't really see a problem with that. Why should we be afraid of high version numbers?

**Comment by dmiotti** [comment]
> It would be nicer for both development and git diff to not include these changes when related data is updated

I definitely vote for 👍🏻 Lowering the number of code lines to review is great. I have the feeling that it would make our life a tiny bit easier too. It can also help not having extra code to write (`, `), usually VSCode does it for me.

> I'm also in favor of applying "real" semantic versioning here and release it as v2. Why should we be afraid of high version numbers?

Agree, I have no objection. I never saw a public package with a high version number. We‘ll see how it goes!

**Comment by frankieyan** [comment]
+1 on trailing commas and proper semver 👍 

A high number is a good indicator on how often we go back and forth on code styling 😉

**Pull request merged**
